<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DDT_CURA_TestSuite_Login</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>55218c95-82f5-4212-90b3-e551d26d8ae4</testSuiteGuid>
   <testCaseLink>
      <guid>a658fc3d-4867-4a42-af12-24a831e4a0fe</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_CURA_Logins/TC_CURA_DDT_Login_01</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>8fcde601-05a9-41fb-821f-f83ff7f03ca9</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/CURA_TestData/CURA_TestData_Excel_Logins</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>8fcde601-05a9-41fb-821f-f83ff7f03ca9</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Username</value>
         <variableId>67542054-76a8-4151-b7b6-fcbf59ce0b72</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>8fcde601-05a9-41fb-821f-f83ff7f03ca9</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>0f65a901-c58f-4259-bc71-f59a847403ad</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
